[systems.visualization.anchored_units]
text.size = 36
text.template = "{0}"
shadow.distance = 2
shadow.density = 0.6
label.offset_multipliers = { x = 0.6, y = 0.72 }
ring.radius_multiplier = 1.8
ring.thickness = 3
ring.label.radius_multiplier = 2.25

[systems.visualization.barriers]
node.size = 16
node.color = "white"
edge.thickness = 8
edge.dash_length = 12
edge.gap_length = 3
edge.color = "pink"

[systems.visualization.colonization]
ring.radius_multiplier = 1.8
ring.thickness = 3
ring.default_alpha = 0.2
